DROP TABLE IF EXISTS "CIDADE";

CREATE TABLE "CIDADE" (
  ID SERIAL PRIMARY KEY,
  DESCRICAO varchar(255)
);

INSERT INTO "CIDADE" (ID,DESCRICAO) VALUES (1,'CRICIUMA'),(2,'ORLEANS'),(3,'TUBARÃO'),(4,'NOVA VENEZA'),(5,'FORQUILHINHA'),(6,'URUSSANGA'),(7,'SIDERÓPOLIS'),(8,'COCAL DO SUL'),(9,'IÇARA'),(10,'RINCÃO');
