DROP TABLE IF EXISTS public.STATUS;

CREATE TABLE public.STATUS (
  ID SERIAL PRIMARY KEY,
  DESCRICAO varchar(255) default NULL
);

INSERT INTO public.STATUS (ID,DESCRICAO) VALUES (1,'ABERTO'),(2,'CANCELADO'),(3,'FATURADO'),(4,'FECHADO'),(5,'PENDENTE');
