DROP TABLE IF EXISTS public.SUB_GRUPO;

CREATE TABLE public.SUB_GRUPO (
  id SERIAL PRIMARY KEY,
  DESCRICAO varchar(255) default NULL
);

INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (1,'SUB-GRUPO 1');
INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (2,'SUB-GRUPO 2');
INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (3,'SUB-GRUPO 3');
INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (4,'SUB-GRUPO 4');
INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (5,'SUB-GRUPO 5');
INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (6,'SUB-GRUPO 6');
INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (7,'SUB-GRUPO 7');
INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (8,'SUB-GRUPO 8');
INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (9,'SUB-GRUPO 9');
INSERT INTO public.SUB_GRUPO (id,DESCRICAO) VALUES (10,'SUB-GRUPO 10');
